
package it.water.authentication.service.rest.spring;

import it.water.authentication.service.rest.AuthenticationRestControllerImpl;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;


/**
 * @Generated by Water Generator
 * Rest Api Class for Authentication entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class AuthenticationSpringRestControllerImpl extends AuthenticationRestControllerImpl implements AuthenticationSpringRestApi {

    @Override
    public Map<String, String> login(String username, String password) {
        return super.login(username, password);
    }
}
