package it.water.authentication.service;

import it.water.authentication.api.AuthenticationApi;
import it.water.authentication.api.AuthenticationSystemApi;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.security.Authenticable;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.service.BaseServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for Authentication entity.
 */
@FrameworkComponent
public class AuthenticationServiceImpl extends BaseServiceImpl implements AuthenticationApi {

    @Inject
    @Getter
    @Setter
    private AuthenticationSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    @Override
    public Authenticable login(String username, String password) {
        return systemService.login(username, password);
    }

    @Override
    public String generateToken(Authenticable authenticable) {
        return systemService.generateToken(authenticable);
    }
}
