package it.water.authentication.service;

import it.water.authentication.api.AuthenticationSystemApi;
import it.water.authentication.api.LoginAttemptStore;
import it.water.authentication.api.options.AuthenticationOption;
import it.water.authentication.service.execption.AccountLockedException;
import it.water.core.api.bundle.ApplicationProperties;
import it.water.core.api.interceptors.OnActivate;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.api.security.Authenticable;
import it.water.core.api.security.AuthenticationProvider;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.permission.exceptions.UnauthorizedException;
import it.water.core.service.BaseSystemServiceImpl;
import it.water.service.rest.api.security.jwt.JwtTokenService;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

import java.util.Collection;
import java.util.Optional;


/**
 * @Generated by Water Generator
 * System Service Api Class for Authentication entity.
 */
@Slf4j
@FrameworkComponent
public class AuthenticationSystemServiceImpl extends BaseSystemServiceImpl implements AuthenticationSystemApi {

    @Inject
    @Setter
    private ComponentRegistry componentRegistry;

    @Inject
    @Setter
    private AuthenticationOption authenticationOption;

    @Inject
    @Setter
    private JwtTokenService jwtTokenService;

    @Inject
    @Setter
    private LoginAttemptStore loginAttemptStore;

    @Inject
    @Setter
    private ApplicationProperties applicationProperties;

    /**
     * On component activation, emit a single prominent WARN if the framework is running in test mode.
     * When water.testMode=true several security controls are intentionally relaxed (login lockout is
     * disabled here, and REST JWT validation is typically disabled via water.rest.security.jwt.validate),
     * so this must never be enabled in a production deployment.
     */
    @OnActivate
    public void onActivate(ApplicationProperties applicationProperties) {
        Object raw = (applicationProperties != null) ? applicationProperties.getProperty(AuthenticationConstants.TEST_MODE) : null;
        boolean testMode = raw != null && Boolean.parseBoolean(raw.toString().trim());
        if (testMode) {
            log.warn("**************************************************************************************");
            log.warn("* WATER TEST MODE IS ENABLED ({}=true)", AuthenticationConstants.TEST_MODE);
            log.warn("* Security controls are DISABLED: login lockout is bypassed and REST JWT validation");
            log.warn("* is typically turned off. DO NOT enable test mode in a production environment.");
            log.warn("**************************************************************************************");
        }
    }

    @Override
    public Authenticable login(String username, String password) {
        return login(username, password, authenticationOption.getIssuerName());
    }

    @Override
    public Authenticable login(String username, String password, String issuerName) {
        //#34 - thin delegation; the real implementation lives in the 4-arg overload (no client IP here)
        return login(username, password, issuerName, null);
    }

    @Override
    public Authenticable login(String username, String password, String authProviderFilter, String clientIp) {
        //#34 - resolve the issuer (null filter falls back to the default) and build an IP-scoped lockout key
        String issuerName = (authProviderFilter != null) ? authProviderFilter : authenticationOption.getIssuerName();
        String ipPart = (clientIp == null || clientIp.isBlank()) ? "unknown" : clientIp.trim();
        String attemptKey = issuerName + ":" + ipPart + ":" + username; //#34 - lockout key: issuer:ip:username
        boolean lockoutEnabled = isLockoutEnabled();

        if (lockoutEnabled && loginAttemptStore.isLocked(attemptKey)) {
            long remaining = loginAttemptStore.remainingLockMillis(attemptKey);
            log.warn("Rejecting login for locked key '{}', {} ms remaining", attemptKey, remaining);
            throw new AccountLockedException(remaining);
        }

        Collection<AuthenticationProvider> authenticationProviders = componentRegistry.findComponents(AuthenticationProvider.class, null);
        //finds the one with highest priority for the specific issuer
        Optional<AuthenticationProvider> authenticationProviderOpt = authenticationProviders.stream().filter(authenticationProvider -> authenticationProvider.issuersNames().contains(issuerName)).findFirst();
        if (authenticationProviderOpt.isEmpty())
            throw new UnauthorizedException("No authentication provider found for " + issuerName);

        Authenticable authenticable;
        try {
            authenticable = authenticationProviderOpt.get().login(username, password);
        } catch (RuntimeException loginError) {
            if (lockoutEnabled)
                loginAttemptStore.recordFailure(attemptKey);
            throw loginError;
        }

        if (authenticable == null) {
            //provider signalled failure without throwing
            if (lockoutEnabled)
                loginAttemptStore.recordFailure(attemptKey);
            throw new UnauthorizedException("Invalid credentials");
        }

        if (lockoutEnabled)
            loginAttemptStore.recordSuccess(attemptKey);
        return authenticable;
    }

    //Lockout is disabled under water.testMode so repeated wrong logins in tests don't trip it
    private boolean isLockoutEnabled() {
        if (applicationProperties == null)
            return true;
        Object raw = applicationProperties.getProperty(AuthenticationConstants.TEST_MODE);
        boolean testMode = raw != null && Boolean.parseBoolean(raw.toString().trim());
        return !testMode;
    }

    @Override
    public String generateToken(Authenticable authenticable) {
        return jwtTokenService.generateJwtToken(authenticable);
    }

    @Override
    public void logout(String token) {
        //reuse the same token service used to generate tokens; revocation is idempotent/safe
        jwtTokenService.revokeToken(token);
    }
}