package it.water.authentication.api;

import it.water.core.api.security.Authenticable;
import it.water.core.api.service.BaseApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods and allows interaction with them through a permission system.
 */
public interface AuthenticationApi extends BaseApi {
    /**
     * Logs with credentials
     * @param username
     * @param password
     * @return
     */
    Authenticable login(String username, String password);

    /**
     * Generates a valid token for an authenticable
     * @param authenticable
     * @return
     */
    String generateToken(Authenticable authenticable);
}