package it.water.authentication.api;

import it.water.core.api.security.Authenticable;
import it.water.core.api.service.BaseApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods and allows interaction with them through a permission system.
 */
public interface AuthenticationApi extends BaseApi {
    /**
     * Logs with credentials
     * @param username
     * @param password
     * @return
     */
    Authenticable login(String username, String password);

    /**
     * Login che propaga il client IP risolto dal controller al system layer per il lockout per-IP (#34).
     * La firma pubblica a due argomenti resta invariata per retro-compatibilità.
     * @param username
     * @param password
     * @param clientIp IP del client risolto dal layer di trasporto (può essere null)
     * @return
     */
    Authenticable login(String username, String password, String clientIp);

    /**
     * Generates a valid token for an authenticable
     * @param authenticable
     * @return
     */
    String generateToken(Authenticable authenticable);

    /**
     * Logs out by revoking the supplied token: its jti is added to the revocation denylist so it
     * is no longer accepted, until its natural expiry. Idempotent and safe on invalid input.
     * @param token raw JWT token to revoke
     */
    void logout(String token);
}