package it.water.authentication.api;

import it.water.core.api.security.Authenticable;
import it.water.core.api.service.BaseSystemApi;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods allows interaction with them bypassing permission system.
 */
public interface AuthenticationSystemApi extends BaseSystemApi {
    /**
     * @param username
     * @param password
     * @return
     */
    Authenticable login(String username, String password);

    /**
     * Logs in providing a specific component filter in order to select the right Authentication Provider if multiple are present
     *
     * @param username
     * @param password
     * @param authProviderFilter
     * @return
     */
    Authenticable login(String username, String password, String authProviderFilter);

    /**
     * Login con dimensione IP per il lockout (#34). L'IP NON va nel SecurityContext: è un dato di
     * trasporto estratto dal controller e passato esplicitamente. Se issuerName è null viene
     * risolto dall'issuer di default; se clientIp è null/blank il lockout degrada alla sola coppia
     * issuer:username (nessuna regressione).
     *
     * @param username
     * @param password
     * @param authProviderFilter issuer/filtro provider (null = issuer di default)
     * @param clientIp IP del client risolto dal layer di trasporto (può essere null)
     * @return
     */
    Authenticable login(String username, String password, String authProviderFilter, String clientIp);

    /**
     * Multi-tenant aware login. Additive overload threading the requested active company to the provider.
     * When the resolved issuer is not in MT mode the companyId is ignored (single-tenant/legacy behavior).
     *
     * @param username
     * @param password
     * @param authProviderFilter issuer/filtro provider (null = issuer di default)
     * @param companyId requested active company (may be null)
     * @param clientIp IP del client risolto dal layer di trasporto (può essere null)
     * @return
     */
    Authenticable login(String username, String password, String authProviderFilter, Long companyId, String clientIp);

    /**
     * User-level impersonation. Resolves the AuthenticationProvider for the default issuer and delegates
     * to it; the provider performs the permission gate (caller must hold IMPERSONATE on WaterUser, admin
     * by construction) and loads the target without a password. No lockout logic here.
     *
     * @param targetUsername username of the user to impersonate
     * @param callerUsername username of the authorized caller (resolved by the Api layer from the context)
     * @param companyId requested active company for the target (may be null → target's primary)
     * @return the target Authenticable, marked as impersonated by the caller
     */
    Authenticable impersonate(String targetUsername, String callerUsername, Long companyId);

    /**
     * Generates a valid token for an authenticable
     *
     * @param authenticable
     * @return
     */
    String generateToken(Authenticable authenticable);

    /**
     * Logs out by revoking the supplied token (adds its jti to the revocation denylist until its
     * natural expiry). Idempotent and safe on invalid/unparseable input.
     *
     * @param token raw JWT token to revoke
     */
    void logout(String token);

}