################################################################
############# AUTHENTICATION MODULE ############################
################################################################

water.authentication.service.issuer=${env:WATER_AUTHENTICATION_SERVICE_ISSUER:-it.water.core.api.model.User}

################################################################
############# KEYSTORE CONFIGURATION ###########################
################################################################

water.keystore.password=${env:WATER_KEYSTORE_PASSWORD:-water.}
water.keystore.alias=${env:WATER_KEYSTORE_ALIAS:-server-cert}
water.keystore.file=${env:WATER_KEYSTORE_FILE:-certs/server.keystore}
water.private.key.password=${env:WATER_PRIVATE_KEY_PASSWORD:-water.}
