package it.water.authentication.service.rest;

import it.water.authentication.api.AuthenticationApi;
import it.water.authentication.api.options.AuthenticationOption;
import it.water.authentication.api.rest.AuthenticationRestApi;
import it.water.authentication.service.ClientIpResolver;
import it.water.core.api.security.Authenticable;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.core.Context;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;


/**
 * @Generated by Water Generator
 * Rest Api Class for Authentication entity.
 */
@FrameworkRestController(referredRestApi = AuthenticationRestApi.class)
public class AuthenticationRestControllerImpl implements AuthenticationRestApi {
    private static Logger log = LoggerFactory.getLogger(AuthenticationRestControllerImpl.class.getName());

    @Inject
    @Setter
    private AuthenticationApi authenticationApi;

    @Inject
    @Setter
    private AuthenticationOption authenticationOption;

    //#34/#37 - per-request HttpServletRequest (javax namespace, JAX-RS/CXF). Used only to read the immediate
    //TCP peer and forwarding headers for the per-IP login lockout key. The Spring controller overrides
    //resolveClientIp() to read the jakarta request instead.
    @Context
    private HttpServletRequest httpServletRequest;

    private static final String BEARER_PREFIX = "Bearer ";

    @Override
    public Map<String, String> login(String username, String password, Long companyId) {
        log.debug("User {} is logging in ...", username);
        Map<String, String> response = new HashMap<>();
        Authenticable authenticable = companyId != null
                ? authenticationApi.login(username, password, companyId, resolveClientIp())
                : authenticationApi.loginForVirtualHost(
                username, password, resolveVirtualHost(), resolveClientIp());
        log.debug("User has logged in succesfully at: {} - {}", username, Instant.now());
        String token = authenticationApi.generateToken(authenticable);
        response.put("token", token);
        return response;
    }

    @Override
    public Map<String, String> impersonate(String targetUsername, Long companyId) {
        //@LoggedIn has already validated the caller's bearer token; the caller is resolved from the context
        //inside the Api layer, and the IMPERSONATE permission gate is enforced in the provider.
        Authenticable authenticable = authenticationApi.impersonate(targetUsername, companyId);
        String token = authenticationApi.generateToken(authenticable);
        log.debug("Impersonation token issued for target {} at: {}", targetUsername, Instant.now());
        Map<String, String> response = new HashMap<>();
        response.put("token", token);
        return response;
    }

    @Override
    public Map<String, String> logout(String authorization) {
        //@LoggedIn has already validated the bearer token by the time we get here
        String token = extractBearerToken(authorization);
        authenticationApi.logout(token);
        log.debug("Token revoked (logout) at: {}", Instant.now());
        Map<String, String> response = new HashMap<>();
        response.put("result", "ok");
        return response;
    }

    /**
     * #34/#37 - Resolves the client IP used as the per-IP lockout key dimension. The JAX-RS/CXF runtime
     * reads the per-request HttpServletRequest injected via {@code @Context} (javax servlet namespace).
     * The trust decision (whether to honor X-Forwarded-For/X-Real-IP) is delegated to {@link ClientIpResolver}
     * using the configured trusted proxies. The Spring controller overrides this to read the jakarta request.
     * @return the resolved client IP, or null if it cannot be determined (system layer maps null to "unknown")
     */
    protected String resolveClientIp() {
        String tcpSource = null;
        String forwardedFor = null;
        String realIp = null;
        try {
            if (httpServletRequest != null) {
                tcpSource = httpServletRequest.getRemoteAddr();
                forwardedFor = httpServletRequest.getHeader("X-Forwarded-For");
                realIp = httpServletRequest.getHeader("X-Real-IP");
            }
        } catch (Exception e) {
            log.trace("Unable to resolve client IP from JAX-RS request: {}", e.getMessage());
        }
        return ClientIpResolver.resolve(trustedProxies(), tcpSource, forwardedFor, realIp);
    }

    /**
     * Resolves the tenant routing key from the HTTP request without trusting a client-supplied company id.
     */
    protected String resolveVirtualHost() {
        try {
            return httpServletRequest == null ? null : httpServletRequest.getServerName();
        } catch (Exception e) {
            log.trace("Unable to resolve virtual host from JAX-RS request: {}", e.getMessage());
            return null;
        }
    }

    //#34/#37 - exposed so runtime subclasses (e.g. Spring) can apply the same trust policy with their own request type
    protected Set<String> trustedProxies() {
        return (authenticationOption != null) ? authenticationOption.getTrustedProxies() : Set.of();
    }

    private String extractBearerToken(String authorization) {
        if (authorization == null)
            return null;
        if (authorization.startsWith(BEARER_PREFIX))
            return authorization.substring(BEARER_PREFIX.length()).trim();
        return authorization.trim();
    }
}
